name: Build and Push Docker Images

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version and build time
        run: |
          if [ ! -f "version.json" ]; then
            echo "version.json not found."
            exit 1
          fi
          version=$(jq -r '.version // "unknown"' version.json)
          build_time=$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')
          jq --arg bt "$build_time" '.build_time = $bt' version.json > version_tmp.json && mv version_tmp.json version.json
          echo "version=$version" >> $GITHUB_ENV
          echo "build_time=$build_time" >> $GITHUB_ENV
        shell: bash

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ env.version }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
